--- # Sample config file
Domain: https://your-jira-domain.com
Username: YourUsername
Password: YourPassword
Project: YourProjectName
Workflow: Ready, Analysis, Analysis Done, Dev, Dev Done, Test, Prod
Types: Epic, User Story, Defect
Custom: 
	- Team: customfield_10001
	- Release: customfield_10002
Filename: Data.csv
