Connection:
  Domain: https://jira.atlassian.com/
  Username: 
  Password: 

Criteria:
  Projects: HCPUB
  Filters: HCPUB Desktop - Closed Major+ Bugs
  Types: Sub-task, Story, Bug

Workflow:
  Ready: Ready Queue, Queue, Open, (Created)
  Dev: Development
  Dev Done: Dev Done
  Test: Test
  Done: Closed, Cancelled

Attributes:
  Team: customfield_10001
  Release: customfield_10002.name
  Stage: status
  Type: issuetype
  Level: priority
  Labels: labels
  Versions: fixVersions
  Components: components
